# Plugin Maven group ID
group=com.keygenqt.vibe.action
# Plugin version
version=0.0.9
# Opt-out flag for bundling Kotlin standard library
kotlin.stdlib.default.dependency=false
# Enable Gradle Configuration Cache
org.gradle.configuration-cache=true
# Enable Gradle Build Cache
org.gradle.caching=true
